name: CI/CD Deploy ERP

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Login no Docker Hub
      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Build e push da imagem
      - name: Build e push Docker image
        run: |
          docker build -t kaylaneguarino/multi-bpo-app-dev:latest .
          docker push kaylaneguarino/multi-bpo-app-dev:latest

      # 4. Deploy no servidor
      - name: Deploy no servidor
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/deploy-scripts
            ./deploy.sh
