name: CI/CD Node.js Docker

on:
  push:
    branches:
      - develop

env:
  DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}
  CONTAINER_NAME: ${{ vars.APP_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy project files to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: ${{ env.DEPLOY_PATH }}

      - name: Build and deploy Docker container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 2222
          script: |
            cd $DEPLOY_PATH
            # Parar e remover container antigo, se existir
            if docker ps -a --format '{{.Names}}' | grep -Eq "^${CONTAINER_NAME}\$"; then
              docker rm -f $CONTAINER_NAME
            fi
            # Build e start do container
            docker-compose up -d --build
