<<<<<<< HEAD
name: CI/CD Node.js Docker
=======
name: ERP Multi BPO Testes
>>>>>>> develop

on:
  push:
    branches:
      - develop

env:
  DEPLOY_PATH: /home/deploy/deploy-erp
  CONTAINER_NAME: erp_multibpo_frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy project files
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "."
          target: ${{ env.DEPLOY_PATH }}

      - name: Build and deploy Docker container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd $DEPLOY_PATH
            docker-compose up -d --build $CONTAINER_NAME
